# Required connection configs for Kafka producer, consumer, and admin
spring:
  kafka:
    properties:
      sasl.mechanism: PLAIN
      bootstrap.servers:
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule
      security.protocol: SASL_SSL

# Best practice for higher availability in Apache Kafka clients prior to 3.0
      session.timeout.ms: 45000

# Required connection configs for Confluent Cloud Schema Registry
      basic.auth.credentials.source: USER_INFO
      basic.auth.user.info:
      schema.registry.url:

topics:
  asset-commercial:
    name: "Asset"
    partitions: 3
    replicas: 3
